# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spell It' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 # Pods for Spell It
 pod 'Charts'
 pod 'Bolts', :inhibit_warnings => true
 pod 'Firebase/Auth'
 pod 'Firebase/Core'
 pod 'Firebase/Storage'
 pod 'Firebase/Firestore', :inhibit_warnings => true
 pod 'Firebase/Auth' , :inhibit_warnings => true
 pod 'SwiftyJSON', :inhibit_warnings => true
 pod 'Alamofire', :inhibit_warnings => true
 pod 'Material', :inhibit_warnings => true
 pod 'ChameleonFramework', :inhibit_warnings => true
 pod 'SVProgressHUD', :inhibit_warnings => true
end
